# Site settings
title: Ryan P.C. McQuen
##email: ryanpcmcquen AT member DOT fsf DOT org
description: Hacker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ryanpcmcquen.org" # the base hostname & protocol for your site
twitter_username: ryanpcmcquen
github_username: ryanpcmcquen

# Build settings
markdown: kramdown
