# Site settings:
title: Ryan P. C. McQuen
description: Hacker.
# The subpath of your site, e.g. /blog/:
baseurl: ""
# The base hostname & protocol for your site:
url: "https://ryanpcmcquen.org"
twitter_username: ryanpcmcquen
github_username: ryanpcmcquen

# Build settings:
markdown: kramdown
